branch-defaults:
  default:
    environment: Mynodeenv1-env
environment-defaults:
  Mynodeenv1-env:
    branch: null
    repository: null
global:
  application_name: my-node-env1
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
