AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 bucket template with join

Parameters: 
  s3BucketName:
    Description: Enter bucket name
    Type: String
    MaxLength: 10
    MinLength: 3
    AllowedPattern: '[A-Za-z]+'
    Default: mywonder

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Join ['-',[!Ref s3BucketName,!Ref AWS::Region,!Ref AWS::StackName]]